async function loadBureauData() {
    const assetList = document.getElementById('asset-list');
    const passportData = document.getElementById('passport-data');

    try {
        // Fetch the manifest generated by your Auto-Cataloger
        const response = await fetch('../manifest.json');
        const data = await response.json();

        // Update Registry
        assetList.innerHTML = data.assets.map(asset => 
            `<li><strong>[${asset.type.toUpperCase()}]</strong> ${asset.name}</li>`
        ).join('');

        // Update Identity (Static fallback for now, dynamic TTL parser next)
        passportData.innerHTML = `
            <p><strong>Architect:</strong> Samuel Muriithi Gitandu, B.S.</p>
            <p><strong>DOI:</strong> 10.5281/zenodo.18894084</p>
            <p><strong>Status:</strong> Fortified</p>
        `;

    } catch (error) {
        console.error("Bureau Sync Error:", error);
        passportData.innerHTML = "Offline: Awaiting Kernel Handshake.";
    }
}

document.addEventListener('DOMContentLoaded', loadBureauData);
